[package]
name = "stm-transformer"
version = "0.1.0"
edition = "2021"

[features]
default = []
cuda = []

[dependencies]
anyhow = "1.0.100"
burn = { version = "0.19.1", features = ["cuda", "train", "wgpu", "ndarray"] }
ndarray = "0.16.1"
ndarray-npy = "0.9.1"
rand = "0.9.2"
